'use client';
import {useEffect,useMemo,useState,useCallback,useRef} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {ArrowLeft,ArrowRight,Check,Pause,Keyboard,ListFilter,Files,Download,Search,Layers,RefreshCw,X,Menu,BarChart3,Settings,Undo2,Trash2,ChevronUp,ChevronDown,CalendarDays,Clock,Wallet,Tag,Plus,PenLine,SlidersHorizontal} from 'lucide-react';
import {pairSuggestions,matchingEntries,parseEdit,mergedIds,type Pair} from '@/lib/reconciliation';
import {type Tx,type Item,type Edit,type Decision,type Report,type Field,defaults,labels,fieldLabels,physical,previousMonth,monthLabel,dateLabel,money,originalEdit,initialEdit,choicesFor,progressRows} from './review-model';
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="filter-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select>}
function PullField({label,value,onOpen,icon,small,className='',disabled=false}:{label:string;value:string;onOpen:()=>void;icon?:React.ReactNode;small?:string;className?:string;disabled?:boolean}){
 const gesture=useRef<{y:number;opened:boolean;timer:ReturnType<typeof setTimeout>|null;pointer:number}|null>(null);
 const suppressClick=useRef(false);
 const clear=()=>{if(gesture.current?.timer)clearTimeout(gesture.current.timer);gesture.current=null};
 useEffect(()=>clear,[]);
 const open=()=>{const g=gesture.current;if(!g||g.opened)return;g.opened=true;suppressClick.current=true;onOpen()};
 return <button type="button" className={'pull-field '+className} aria-label={`Edit ${label}: ${value}`} disabled={disabled}
 onContextMenu={e=>e.preventDefault()}
 onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}onOpen()}}
 onPointerDown={e=>{if(e.button!==0)return;clear();suppressClick.current=false;const g={y:e.clientY,opened:false,timer:null as ReturnType<typeof setTimeout>|null,pointer:e.pointerId};gesture.current=g;e.currentTarget.setPointerCapture(e.pointerId);g.timer=setTimeout(open,300)}}
 onPointerMove={e=>{const g=gesture.current;if(!g||e.pointerId!==g.pointer)return;const dy=g.y-e.clientY;if(!g.opened&&dy>18)open();if(g.opened){document.querySelector<HTMLElement>('[data-field-options]')?.scrollBy({top:dy,behavior:'instant'});g.y=e.clientY}}}
 onPointerUp={()=>clear()} onPointerCancel={()=>{suppressClick.current=true;clear()}}>
 <span className="field-caption">{icon}{label}</span><strong>{value}</strong>{small&&<small>{small}</small>}<ChevronUp size={16} className="pull-chevron"/></button>
}
export default function Workspace(){
 const [report,setReport]=useState<Report|null>(null),[decisions,setDecisions]=useState<Record<string,Decision>>({}),[keys,setKeys]=useState(defaults),[catalogue,setCatalogue]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [month,setMonth]=useState(previousMonth),[bank,setBank]=useState('all'),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[index,setIndex]=useState(0),[targetId,setTargetId]=useState<string|null>(null),[edit,setEdit]=useState<Edit|null>(null),[note,setNote]=useState('');
 const [view,setView]=useState('review'),[menu,setMenu]=useState(false),[help,setHelp]=useState(false),[files,setFiles]=useState(false),[mmOpen,setMmOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[captured,setCaptured]=useState(''),[escapeArmed,setEscapeArmed]=useState(false),[queuePage,setQueuePage]=useState(0),[mmPage,setMmPage]=useState(0);
 const [field,setField]=useState<Field|null>(null),[entryPicker,setEntryPicker]=useState(false),[optionSearch,setOptionSearch]=useState(''),[custom,setCustom]=useState(''),[deleteOpen,setDeleteOpen]=useState(false),[revertOpen,setRevertOpen]=useState(false),[dragX,setDragX]=useState(0),[exportOpen,setExportOpen]=useState(false),[exporting,setExporting]=useState(false),[pairOpen,setPairOpen]=useState(false),[bankDetails,setBankDetails]=useState(false);
 const swipe=useRef<{x:number;y:number}|null>(null),drafts=useRef<Record<string,{targetId:string|null;edit:Edit;note:string}>>({}),saveLock=useRef(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [r,d,s,c]=await Promise.all(['/api/reconciliation','/api/decisions','/api/settings','/api/catalogue'].map(async p=>{const response=await fetch(p);const j:any=await response.json();if(!response.ok)throw Error(j.error||'Could not load the workspace');return j}));const enriched=await (await import('@/lib/backup-export')).enrichReport(r);setReport(enriched);setDecisions(Object.fromEntries(d.map((x:Decision)=>[x.id,x])));setCatalogue(c.categories||[]);setKeys({...defaults,...Object.fromEntries(s.filter((x:any)=>x.key.startsWith('keyboard_')).map((x:any)=>[x.key.slice(9),x.value]))});}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
 const consumed=useMemo(()=>{const ids=new Map<string,string>();for(const d of Object.values(decisions))if(d.status==='confirmed')for(const id of mergedIds(d.id,parseEdit(d).merge))if(id!==d.id)ids.set(id,d.id);return ids},[decisions]);
 const filtered=useMemo(()=>report?.items.filter(i=>!consumed.has(i.id)&&i.source.date.startsWith(month)&&(bank==='all'||i.source.bank===bank)&&(status==='all'||(status==='suggested'?i.candidates.length>0:status==='unmatched'?i.candidates.length===0:status==='deleted'?decisions[i.id]?.action==='delete':(decisions[i.id]?.status||'unresolved')===status))&&(!search||[i.source.description,i.source.account,i.source.amount,i.source.currency].join(' ').toLowerCase().includes(search.toLowerCase())))||[],[report,month,bank,status,search,decisions,consumed]);
 const rawCurrent=filtered[Math.min(index,Math.max(0,filtered.length-1))];
 const pairs=useMemo(()=>rawCurrent&&report?pairSuggestions(rawCurrent,report):[],[rawCurrent,report]);
 const activePair=pairs.find(p=>p.purchase.id===edit?.merge?.purchaseId&&p.roundUp.id===edit?.merge?.roundUpId);
 const current=useMemo(()=>{if(!rawCurrent||!report)return rawCurrent;const extra=matchingEntries(activePair?.purchase||rawCurrent,report,activePair?.total);return {...rawCurrent,candidates:[...new Map([...(activePair?[]:rawCurrent.candidates),...extra].map(c=>[c.target.id,c])).values()].sort((a,b)=>b.score-a.score)}},[rawCurrent,report,activePair]);
 const decision=current?decisions[current.id]:undefined,match=current?.candidates.find(c=>c.target.id===targetId),isNew=!targetId,isDeleted=decision?.action==='delete';
 const required=edit?[...(!edit.accountId?['account']:[]),...(edit.kind==='transfer'?!edit.targetAccountId?['target account']:[]:!edit.category?['category']:[]),...(!edit.description.trim()?['note']:[])]:[];
 const persistLocalDraft=()=>{if(current&&edit)drafts.current[current.id]={targetId,edit:{...edit},note}};
 const go=(nextView:string)=>{if(busy)return;persistLocalDraft();setView(nextView);setMenu(false);setNotice('')};
 const move=(step:number)=>{if(busy)return;persistLocalDraft();setIndex(i=>filtered.length?(i+step+filtered.length)%filtered.length:0);setNotice('');setDragX(0)};
 useEffect(()=>{setIndex(0);setQueuePage(0)},[month,bank,status,search]);
 useEffect(()=>{if(!current){setEdit(null);return;}const d=drafts.current[current.id]||initialEdit(current,decisions[current.id],report?.accounts);setTargetId(d.targetId);setEdit(d.edit);setNote(d.note);setDragX(0)},[current?.id]);
 const changeMonth=(v:string)=>{if(busy)return;persistLocalDraft();setMonth(v);setIndex(0)};
 const chooseTarget=(id:string|null)=>{if(!current)return;setTargetId(id);const next=originalEdit(current,id,report?.accounts);if(activePair){next.amount=activePair.total;next.kind='expense';next.description=activePair.purchase.source.description;next.date=activePair.purchase.source.date;next.time=next.time||'23:59';next.merge=edit?.merge;next.memo=[next.memo,mergeDescription(activePair)].filter(Boolean).join('\n')}setEdit(next);setEntryPicker(false);setNotice('')};
 const mergeDescription=(p:Pair)=>`Merged purchase ${money(p.purchase.source)} + Lommepenger round-up ${money(p.roundUp.source)}.`;
 const usePair=(p:Pair)=>{if(!current||!report)return;const found=matchingEntries(p.purchase,report,p.total)[0];const id=found?.target.id||null;const pairItem={...p.purchase,candidates:found?[found]:[]};const next=originalEdit(pairItem,id,report.accounts);next.amount=p.total;next.kind='expense';next.date=p.purchase.source.date;next.description=p.purchase.source.description;next.merge={purchaseId:p.purchase.id,roundUpId:p.roundUp.id,...(p.credit?{creditId:p.credit.id}:{})};next.memo=[next.memo,mergeDescription(p)].filter(Boolean).join('\n');setTargetId(id);setEdit(next);setPairOpen(false);setNotice('Pair selected. Check the account, category and amount, then confirm.')};
 const removePair=()=>{if(!current)return;setTargetId(null);setEdit(originalEdit(current,null,report?.accounts));setNotice('Pair removed')};
 const openField=(f:Field)=>{if(!edit||isDeleted||busy)return;setField(f);setOptionSearch('');setCustom(String(edit[f]??''));};
 const applyField=(value:string)=>{if(!field||!edit||!report)return;if(field==='accountId'||field==='targetAccountId'){const account=report.accounts.find(a=>a.id===value);if(!account)return;setEdit(field==='targetAccountId'?{...edit,targetAccountId:account.id,targetAccount:account.name}:{...edit,accountId:account.id,account:account.name})}else if(field==='amount'){const amount=Number(value.replace(',','.'));if(!Number.isFinite(amount)){setError('Enter a valid amount');return;}setEdit({...edit,amount:edit.kind==='income'?Math.abs(amount):-Math.abs(amount)})}else{setEdit({...edit,[field]:value})}setField(null);setError('');setNotice('')};
 const save=async(action:string,nextStatus='confirmed')=>{if(!current||!edit||saveLock.current)return false;saveLock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/decisions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current.id,targetId,status:nextStatus,note,action,proposedEdit:edit})});const result:any=await r.json();if(!r.ok)throw Error(result.error);setDecisions(d=>({...d,[current.id]:result}));const reset=initialEdit(current,result,report?.accounts);setEdit(reset.edit);setTargetId(reset.targetId);setNote(reset.note);delete drafts.current[current.id];setNotice(action==='revert'?'Restored the original values.':action==='delete'?(targetId?'Deletion saved to your draft.':'New entry dismissed.'):nextStatus==='held'?'Skipped. Find it later in Queue → Skipped.':isNew?'New entry confirmed in your draft.':'Edit confirmed in your draft.');setDeleteOpen(false);setRevertOpen(false);return true;}catch(e){setError((e as Error).message);return false}finally{setBusy(false);saveLock.current=false}};
 const skip=async()=>{if(isDeleted)return;const next=filtered.slice(index+1).concat(filtered.slice(0,index)).find(i=>!decisions[i.id]||decisions[i.id].status==='unresolved');if(await save(isNew?'create':'edit','held')){if(next){setIndex(filtered.filter(i=>!['unresolved','confirmed','deleted'].includes(status)||i.id!==current?.id).findIndex(i=>i.id===next.id));setDragX(0)}else{setStatus('held');setView('queue')}setNotice('Skipped. Find it later in Queue → Skipped.')}};
 const saveKeys=async(next:Record<string,string>)=>{try{const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mapping:next})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setKeys(next);setEditing(null);setError('');}catch(e){setError((e as Error).message)}};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.metaKey||e.ctrlKey||e.altKey)return;const k=physical[e.code]||(e.code.startsWith('Key')?e.code.slice(3):e.key.toUpperCase());if(editing){e.preventDefault();if(e.key==='Escape'){if(escapeArmed)setEditing(null);else{setCaptured(defaults[editing]);setEscapeArmed(true)}}else if(e.key==='Enter'){void saveKeys({...keys,[editing]:captured})}else if(!['Shift','Control','Alt','Meta'].includes(e.key)){setCaptured(k);setEscapeArmed(false)}return;}if(['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)||(e.target as HTMLElement).isContentEditable)return;if(help||files||mmOpen||menu||field||entryPicker||deleteOpen||revertOpen||pairOpen||bankDetails||exportOpen)return;if(k===keys.help){e.preventDefault();setHelp(true)}else if(k===keys.queue){e.preventDefault();go(view==='queue'?'review':'queue')}else if(view!=='review')return;else if(k===keys.previous){e.preventDefault();move(-1)}else if(k===keys.next){e.preventDefault();move(1)}else if(k===keys.skip){e.preventDefault();void skip()}else if(k===keys.save&&!isDeleted){e.preventDefault();void save(isNew?'create':'edit')}else if(k===keys.fieldUp){e.preventDefault();openField('amount')}else if(k===keys.fieldLeft){e.preventDefault();openField('accountId')}else if(k===keys.fieldDown){e.preventDefault();openField('category')}else if(k===keys.fieldRight){e.preventDefault();setEntryPicker(true)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[editing,captured,escapeArmed,keys,help,view,files,mmOpen,menu,field,entryPicker,deleteOpen,revertOpen,current,targetId,edit,note,busy,index,isDeleted,pairOpen,bankDetails,exportOpen]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'filter_reconciliation_queue',description:'Filter the visible queue within the selected month. Never confirms or deletes entries.',inputSchema:{type:'object',properties:{search:{type:'string'},bank:{type:'string',enum:['all','revolut','nordea']},month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['search','bank','month'].includes(k))||('search'in input&&typeof input.search!=='string')||('bank'in input&&!['all','revolut','nordea'].includes(input.bank))||('month'in input&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(input.month)))throw Error('Invalid queue filter');if('search'in input)setSearch(input.search);if(input.bank)setBank(input.bank);if(input.month)setMonth(input.month);return {applied:true,...input}}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 const months=useMemo(()=>[...new Set([previousMonth(),month,...(report?.items.map(i=>i.source.date.slice(0,7))||[])])].sort().reverse(),[report,month]);
 const categories=useMemo(()=>report?.categoryOptions?.length?report.categoryOptions.filter(c=>c.kind===(edit?.kind||'expense')).map(c=>c.name).filter((v,i,a)=>a.indexOf(v)===i).sort():[...new Set([...catalogue,...(report?.items.flatMap(i=>i.candidates.map(c=>c.target.category))||[]),...(report?.moneyManagerOnly.map(t=>t.category)||[])])].filter(Boolean).sort(),[report,catalogue,edit?.kind]);
 const options=useMemo(()=>field&&current&&report?choicesFor(field,current,report,categories).filter(o=>field!=='category'||categories.includes(o.value)).map(o=>field==='targetAccountId'&&o.value===edit?.accountId?{...o,disabled:true,detail:'Choose a different account'}:o).filter(o=>!optionSearch||(o.label+' '+o.detail).toLowerCase().includes(optionSearch.toLowerCase())):[],[field,current,report,categories,optionSearch,edit?.accountId]);
 const monthItems=useMemo(()=>report?.items.filter(i=>i.source.date.startsWith(month))||[],[report,month]);
 const accountProgress=useMemo(()=>progressRows(monthItems,decisions,i=>i.source.account),[monthItems,decisions]);
 const monthProgress=useMemo(()=>progressRows(report?.items||[],decisions,i=>i.source.date.slice(0,7)).reverse(),[report,decisions]);
 const done=monthItems.filter(i=>decisions[i.id]?.status==='confirmed'||consumed.has(i.id)).length;
 const mmMonth=report?.moneyManagerOnly.filter(t=>t.date.startsWith(month))||[];
 const downloadBackup=async()=>{if(!report||exporting)return;setExporting(true);setError('');try{const {bytes,summary}=await (await import('@/lib/backup-export')).exportBackup(report);const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download='bankbuddy-reviewed-'+new Date().toISOString().slice(0,10)+'.mmbak';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice(`Backup exported: ${summary.added} added, ${summary.edited} edited, ${summary.deleted} deleted, ${summary.dismissed} dismissed.`);setExportOpen(false)}catch(e){setError((e as Error).message)}finally{setExporting(false)}};
 const exportDecisions=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),decisions:Object.values(decisions)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='bankbuddy-draft-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 if(loading)return <main className="load-state"><div className="brandmark">B</div><h1>BankBuddy</h1><p>Loading your private workspace…</p></main>;
 if(!report)return <main className="load-state"><h1>BankBuddy</h1><p role="alert">{error}</p><button onClick={load}><RefreshCw size={16}/>Retry</button></main>;
 return <main className={"swipe-app money-manager compact-dark view-"+view}>
 <header className="app-header"><button className="menu-toggle" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={24}/></button><div className="app-brand"><div className="brandmark">B</div><h1>BankBuddy</h1></div><span className="source-bank">{current?.source.bank||"Private"}</span></header>
 <div className="month-header"><span><CalendarDays size={16}/>REVIEWING</span><Pick value={month} onChange={changeMonth} label="Selected month" options={months.map(m=>[m,monthLabel(m)])}/></div>
 {error&&<div className="message error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="message" role="status">{notice}</div>}
 {view==='review'&&<section className="review-view">
  <div className="deck-meta"><span>{filtered.length?Math.min(index+1,filtered.length):0} <small>of {filtered.length.toLocaleString()}</small></span><button onClick={()=>go('queue')}><SlidersHorizontal size={15}/>{bank==='all'?'All banks':bank}{status!=='all'?' · '+status:''}</button></div>
  {current&&edit?<>
  <article aria-label={isNew?'New Money Manager entry':'Edit Money Manager entry'} className={'expense-card '+(isNew?'create-card':'edit-card')+(isDeleted?' deleted-card':'')} style={{transform:`translateX(${dragX}px) rotate(${dragX/45}deg)`}} onPointerDown={e=>{if(busy||(e.target as HTMLElement).closest('button,input,textarea,a'))return;swipe.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!swipe.current)return;const dx=e.clientX-swipe.current.x,dy=e.clientY-swipe.current.y;if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>8)setDragX(Math.max(-120,Math.min(120,dx)))}} onPointerUp={e=>{if(!swipe.current)return;const dx=e.clientX-swipe.current.x,dy=e.clientY-swipe.current.y;swipe.current=null;setDragX(0);if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)move(dx<0?1:-1)}} onPointerCancel={()=>{swipe.current=null;setDragX(0)}}>
   <div className="expense-card-top"><div><h2>{edit.kind==='income'?'Income':edit.kind==='transfer'?'Transfer':'Expense'}</h2><span className="operation-label">{isNew?'New entry':'Update existing entry'}{decision?.status==='confirmed'?' · Saved':''}</span></div><button className="big-check" aria-label={isNew?'Confirm new entry':'Confirm edits'} title={required.length?'Choose '+required.join(' and '):'Confirm changes'} disabled={busy||isDeleted||!!required.length} onClick={()=>save(isNew?'create':'edit')}>{busy?<RefreshCw size={28} className="animate-spin"/>:<Check size={34} strokeWidth={3}/>}</button></div>
   <div className="entry-tabs" aria-label="Transaction type">{(['income','expense','transfer'] as const).map(kind=><button key={kind} disabled={busy||isDeleted||!!activePair} aria-pressed={edit.kind===kind} onClick={()=>setEdit({...edit,kind,amount:kind==='income'?Math.abs(edit.amount):-Math.abs(edit.amount),category:'',memo:isNew&&kind==='expense'?'Newly created expense (BankBuddy)':edit.memo})}>{kind[0].toUpperCase()+kind.slice(1)}</button>)}</div>
   <div className="simple-form">
    <div className="form-date"><PullField disabled={busy||isDeleted} label="Date" value={dateLabel(edit.date)} onOpen={()=>openField('date')}/><PullField disabled={busy||isDeleted} label="Time" value={edit.time?.slice(0,5)||'23:59'} onOpen={()=>openField('time')}/></div>
    <PullField disabled={busy||isDeleted} label={edit.kind==='transfer'?'From':'Account'} value={report.accounts.find(a=>a.id===edit.accountId)?.name||'Choose account *'} className={!edit.accountId?'required-field':''} onOpen={()=>openField('accountId')}/>
    {edit.kind==='transfer'?<PullField disabled={busy||isDeleted} label="To" value={report.accounts.find(a=>a.id===edit.targetAccountId)?.name||'Choose target account *'} className={!edit.targetAccountId?'required-field':''} onOpen={()=>openField('targetAccountId')}/>:<PullField disabled={busy||isDeleted} label="Category" value={edit.category||'Choose category *'} className={!edit.category?'required-field':''} onOpen={()=>openField('category')}/>}
    <PullField disabled={busy||isDeleted||!!activePair} label="Amount" value={money({...edit,amount:Math.abs(edit.amount)})} onOpen={()=>openField('amount')}/>
    <label className="form-input"><span>Note</span><input aria-label="Expense note" value={edit.description} disabled={busy||isDeleted} onChange={e=>setEdit({...edit,description:e.target.value})} placeholder="Shop or expense name *" maxLength={500}/></label>
    <label className="form-input description-input"><span>Description</span><textarea aria-label="Expense description" value={edit.memo||''} disabled={busy||isDeleted} onChange={e=>setEdit({...edit,memo:e.target.value})} placeholder="Optional details" maxLength={4000} rows={1}/></label>
   </div>
   <p className="required-hint" role="status">{isDeleted?'Deleted. Revert to restore.':required.length?'Choose '+required.join(' and ')+', then tap ✓.':'Ready to confirm with ✓.'}</p>
   <div className="reconciliation-options">
    <button className="entry-link" disabled={busy||isDeleted} onClick={()=>setEntryPicker(true)}>{match?'Updating: '+(match.target.description||'existing entry'):'Create a new Money Manager entry'}<ChevronDown size={15}/></button>
    {activePair?<div className="merge-summary"><span>{money({...activePair.purchase.source,amount:Math.abs(activePair.purchase.source.amount)})} + {money({...activePair.roundUp.source,amount:Math.abs(activePair.roundUp.source.amount)})} = {money({...edit,amount:Math.abs(activePair.total)})}</span><small className="merge-credit">{activePair.credit?'The matching pocket credit is included in this review.':'No unique matching pocket credit found; review the incoming pocket transaction separately.'}</small><button disabled={busy||isDeleted} onClick={removePair}>Undo pairing</button></div>:!!pairs.length&&<button className="roundup-link" disabled={busy||isDeleted} onClick={()=>setPairOpen(true)}>Possible purchase + round-up <ChevronDown size={15}/></button>}
    <button className="bank-details-button" onClick={()=>setBankDetails(true)}>Bank details</button>
   </div>
   <div className="card-actions"><button disabled={busy} onClick={()=>setRevertOpen(true)}><Undo2 size={19}/><span>Revert</span></button><button disabled={busy||isDeleted} onClick={()=>void skip()}><Pause size={19}/><span>Skip</span></button><button className="delete-action" disabled={busy||isDeleted} onClick={()=>setDeleteOpen(true)}><Trash2 size={19}/><span>Delete</span></button></div>
  </article>
  <div className="swipe-controls"><button disabled={busy} onClick={()=>move(-1)} aria-label="Previous transaction"><ArrowLeft size={22}/></button><span>Hold a field and slide to choose</span><button disabled={busy} onClick={()=>move(1)} aria-label="Next transaction"><ArrowRight size={22}/></button></div>

  </>:<div className="empty-state"><CalendarDays size={34}/><h2>No transactions in this view</h2><p>{monthLabel(month)} is selected.</p><button onClick={()=>{setSearch('');setBank('all');setStatus('all')}}>Clear filters</button></div>}
 </section>}
 {view==='queue'&&<section className="secondary-view"><div className="view-heading"><h2>Match queue</h2><span>{filtered.length.toLocaleString()} transactions</span></div><div className="queue-filters"><div className="search"><Search size={17}/><input aria-label="Search transactions" placeholder="Merchant, account or amount" value={search} onChange={e=>{persistLocalDraft();setSearch(e.target.value)}}/></div><Pick label="Bank" value={bank} onChange={v=>{persistLocalDraft();setBank(v)}} options={[["all","All banks"],["revolut","Revolut"],["nordea","Nordea"]]}/><Pick label="Status" value={status} onChange={v=>{persistLocalDraft();setStatus(v)}} options={[["all","All transactions"],["unresolved","To review"],["confirmed","Confirmed"],["held","Skipped"],["deleted","Deleted in draft"],["suggested","Has candidates"],["unmatched","No candidates"]]}/></div><div className="queue-list">{filtered.slice(queuePage*40,(queuePage+1)*40).map((i,n)=><button key={i.id} onClick={()=>{persistLocalDraft();setIndex(queuePage*40+n);setView('review')}}><span className={'queue-type '+(i.candidates.length?'orange':'green')}>{i.candidates.length?<PenLine size={17}/>:<Plus size={17}/>}</span><span><strong>{i.source.description}</strong><small>{i.source.date} · {i.source.account}</small></span><span><strong>{money(i.source)}</strong><small>{decisions[i.id]?.action==='delete'?'Deleted in draft':decisions[i.id]?.status==='held'?'Skipped':decisions[i.id]?.status||'To review'}</small></span></button>)}</div><div className="pagination"><button disabled={!queuePage} onClick={()=>setQueuePage(p=>p-1)}>Previous</button><span>Page {queuePage+1} / {Math.max(1,Math.ceil(filtered.length/40))}</span><button disabled={(queuePage+1)*40>=filtered.length} onClick={()=>setQueuePage(p=>p+1)}>Next</button></div></section>}
 {view==='progress'&&<section className="secondary-view"><div className="view-heading"><h2>Progress</h2><span>{monthLabel(month)}</span></div><div className="progress-summary"><strong>{monthItems.length?Math.round(done/monthItems.length*100):0}%</strong><div><h3>{done.toLocaleString()} of {monthItems.length.toLocaleString()} reviewed</h3><p>Confirmed edits, new entries and deletions.</p></div></div><h3 className="breakdown-title">By account · {monthLabel(month)}</h3><div className="breakdown-list">{accountProgress.map(row=><div key={row.name}><header><strong>{row.name}</strong><span>{row.done}/{row.total}</span></header><Progress value={row.total?row.done/row.total*100:0}/><small>{row.held} skipped · {row.total-row.done-row.held} to review</small></div>)}</div><h3 className="breakdown-title">By month</h3><div className="breakdown-list">{monthProgress.map(row=><button key={row.name} onClick={()=>changeMonth(row.name)}><header><strong>{monthLabel(row.name)}</strong><span>{row.done}/{row.total}</span></header><Progress value={row.done/row.total*100}/></button>)}</div></section>}
 {view==='settings'&&<section className="secondary-view"><div className="view-heading"><h2>Settings</h2><span>Private workspace</span></div><div className="settings-links"><button onClick={()=>setHelp(true)}><Keyboard/><span><strong>Keyboard controls</strong><small>Norwegian layout · customize your shortcuts</small></span><ChevronUp/></button><button onClick={()=>setFiles(true)}><Files/><span><strong>Original sources</strong><small>All {report.files.length} files, preserved unchanged</small></span><ChevronUp/></button><button onClick={()=>setExportOpen(true)}><Download/><span><strong>Download reviewed backup</strong><small>Apply confirmed changes to a new Money Manager backup</small></span></button><button onClick={exportDecisions}><Download/><span><strong>Export draft decisions</strong><small>Edits, additions, deletions and notes as JSON</small></span></button><button onClick={()=>{setMmPage(0);setMmOpen(true)}}><Layers/><span><strong>Money Manager without candidates</strong><small>{mmMonth.length.toLocaleString()} entries in {monthLabel(month)}</small></span><ChevronUp/></button></div><div className="settings-note"><h3>Your draft and your backup</h3><p>The green check confirms a change in BankBuddy’s draft. Delete marks an existing entry for deletion or dismisses a new entry. Revert restores the original values.</p><p>Download a reviewed backup to apply confirmed changes. Held and unconfirmed edits are excluded. Your imported original is never modified.</p></div></section>}
 <nav className="bottom-nav" aria-label="Main navigation">{[{id:'review',label:'Review',Icon:Layers},{id:'queue',label:'Queue',Icon:ListFilter},{id:'progress',label:'Progress',Icon:BarChart3},{id:'settings',label:'Settings',Icon:Settings}].map(({id,label,Icon})=><button key={id} disabled={busy} onClick={()=>go(id)} aria-current={view===id?'page':undefined} className={view===id?'active':''}><Icon size={24}/><span>{label}</span></button>)}</nav>
 <Sheet open={menu} onOpenChange={setMenu}><SheetContent side="left" className="app-menu"><SheetHeader><SheetTitle>BankBuddy</SheetTitle><SheetDescription>{monthLabel(month)} · private workspace</SheetDescription></SheetHeader><button onClick={()=>go('review')}><Layers/>Review cards</button><button onClick={()=>go('queue')}><ListFilter/>Match queue</button><button onClick={()=>go('progress')}><BarChart3/>Progress by account and month</button><button onClick={()=>go('settings')}><Settings/>Settings and sources</button><button onClick={()=>{setMenu(false);exportDecisions()}}><Download/>Export draft</button></SheetContent></Sheet>
 <Dialog open={bankDetails} onOpenChange={setBankDetails}><DialogContent className="bank-dialog"><DialogHeader><DialogTitle>Bank details</DialogTitle><DialogDescription>Original statement entry and your review note.</DialogDescription></DialogHeader>{current&&<><p>{current.source.description}</p><p>{money(current.source)} · {dateLabel(current.source.date)}</p><p>{current.source.account}</p><label>Review note<input aria-label="Review note" value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label>{activePair&&<p>{activePair.credit?'The matching pocket credit is included.':'Review the incoming pocket transaction separately.'}</p>}</>}</DialogContent></Dialog>
 <Sheet modal={false} open={!!field} onOpenChange={o=>{if(!o)setField(null)}}><SheetContent side="bottom" className="field-sheet" onOpenAutoFocus={e=>e.preventDefault()} onInteractOutside={e=>{if((e.target as HTMLElement)?.closest?.('.pull-field'))e.preventDefault()}}><div className="sheet-grip"/><SheetHeader><SheetTitle>{field?field==='description'?'Note':fieldLabels[field]:''} options</SheetTitle><SheetDescription>Hold and drag up from a field, or scroll this list. Percentages show match strength, not statistical probabilities.</SheetDescription></SheetHeader>{field&&<><div className="search option-search"><Search size={16}/><input aria-label="Search field options" value={optionSearch} onChange={e=>setOptionSearch(e.target.value)} placeholder="Find an option…"/></div><div className="field-options" data-field-options role="list">{options.map(o=><button role="listitem" key={o.value} className={String(edit?.[field])===o.value?'chosen':''} disabled={o.disabled} onClick={()=>applyField(o.value)}><span><strong>{o.label}</strong><small>{o.detail}</small></span><b>{o.score}%</b>{String(edit?.[field])===o.value&&<Check size={17}/>}</button>)}{!options.length&&<p>No matching options.</p>}</div>{field!=='accountId'&&field!=='targetAccountId'&&field!=='category'&&<form className="custom-field" onSubmit={e=>{e.preventDefault();applyField(custom)}}><label>{'Enter '+(field==='description'?'note':fieldLabels[field].toLowerCase())}<input aria-label={'Custom '+(field==='description'?'Note':fieldLabels[field])} type={field==='date'?'date':field==='time'?'time':field==='amount'?'number':'text'} step={field==='amount'?'0.01':undefined} value={custom} onChange={e=>setCustom(e.target.value)} required={true} maxLength={500}/></label><button type="submit">Use value</button></form>}</>}</SheetContent></Sheet>
 <Sheet open={pairOpen} onOpenChange={setPairOpen}><SheetContent side="bottom" className="field-sheet"><SheetHeader><SheetTitle>Pair purchase and round-up</SheetTitle><SheetDescription>Suggestions only. Check the purchase and amount before selecting.</SheetDescription></SheetHeader><div className="field-options">{pairs.map(p=>{const used=mergedIds(current?.id||'',{purchaseId:p.purchase.id,roundUpId:p.roundUp.id,creditId:p.credit?.id}).some(id=>consumed.has(id)||id!==current?.id&&decisions[id]?.status==='confirmed');return <button key={p.purchase.id+p.roundUp.id} disabled={used} onClick={()=>usePair(p)}><span><strong>{p.purchase.source.description}</strong><small>{money(p.purchase.source)} + {money(p.roundUp.source)} = {money({...p.purchase.source,amount:p.total})}</small><small>{used?'Already included in a confirmed review':p.reason}</small></span><b>{p.score}%</b></button>})}</div></SheetContent></Sheet>
 <Sheet open={entryPicker} onOpenChange={setEntryPicker}><SheetContent side="bottom" className="field-sheet"><div className="sheet-grip"/><SheetHeader><SheetTitle>Choose the Money Manager entry</SheetTitle><SheetDescription>Editing an existing entry is orange. Creating a new entry is green.</SheetDescription></SheetHeader><div className="field-options">{current?.candidates.map(c=><button key={c.target.id} className={targetId===c.target.id?'chosen':''} onClick={()=>chooseTarget(c.target.id)}><span><strong>{c.target.description||'Unlabelled'} · {money(c.target)}</strong><small>{c.target.account} · {c.target.date} · {c.target.time||'23:59'}</small><small>{c.reason}</small></span><b>{c.score}%</b></button>)}<button className="create-option" onClick={()=>chooseTarget(null)}><Plus size={22}/><span><strong>Create a new entry</strong><small>Start from the bank statement</small></span></button></div></SheetContent></Sheet>
 <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent className="bank-dialog"><AlertDialogHeader><AlertDialogTitle>{isNew?'Dismiss this new entry?':'Delete this entry from the draft?'}</AlertDialogTitle><AlertDialogDescription>{isNew?'The bank statement will stay in your queue, marked as dismissed.':'The selected Money Manager entry will be marked for deletion in your draft.'} You can restore it with Revert. The original backup is unchanged.</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="pink">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void save('delete')}}>Delete from draft</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={revertOpen} onOpenChange={setRevertOpen}><AlertDialogContent className="bank-dialog"><AlertDialogHeader><AlertDialogTitle>Restore the original values?</AlertDialogTitle><AlertDialogDescription>This removes saved and unsaved changes, clears the note, and reopens this transaction for review.</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="pink">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void save('revert')}}>Restore original</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={exportOpen} onOpenChange={o=>{if(!exporting)setExportOpen(o)}}><DialogContent className="bank-dialog"><DialogHeader><DialogTitle>Download reviewed backup</DialogTitle><DialogDescription>Apply all confirmed changes across all months to a new .mmbak file. Held and unconfirmed changes are excluded.</DialogDescription></DialogHeader><p>Existing entries keep their stored exchange-rate ratio. New entries use the rates saved in the imported backup, which may differ from historical rates. Transfers require two accounts in the same currency.</p><p>The export is checked for database integrity. Restoring it in the Money Manager app has not been verified; keep your original backup.</p>{error&&<p role="alert" className="pink">{error}</p>}<button disabled={exporting} onClick={downloadBackup}><Download/>{exporting?'Building backup…':'Download confirmed changes'}</button></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={o=>{setHelp(o);if(!o)setEditing(null)}}><DialogContent onEscapeKeyDown={e=>{if(editing)e.preventDefault()}} className="bank-dialog sm:max-w-3xl"><DialogHeader><DialogTitle>Norwegian keyboard controls</DialogTitle><DialogDescription>Choose a command, press its new key, then Enter to save. Each command needs a unique key.</DialogDescription></DialogHeader>{editing&&<div className="capture">Editing {labels[editing]} <kbd>{captured||'Press a key'}</kbd><small>Enter confirms. Escape loads the default; Escape again cancels.</small></div>}<div className="shortcuts">{Object.entries(labels).map(([k,l])=><button key={k} className={editing===k?'active':''} onClick={()=>{setEditing(k);setCaptured(keys[k]);setEscapeArmed(false)}}><kbd>{keys[k]}</kbd><span>{l}</span></button>)}</div><div className="keyboard-diagram" aria-label="Norwegian keyboard reference">{['Q W E R T Y U I O P Å ^','A S D F G H J K L Ø Æ','Z X C V B N M'].map(row=><div key={row}>{row.split(' ').map(k=><span key={k} className={Object.values(keys).includes(k)?'bound':''}>{k}</span>)}</div>)}</div>{error&&<p role="alert" className="pink">{error}</p>}<button onClick={()=>saveKeys(defaults)}>Reset shortcuts</button></DialogContent></Dialog>
 <Dialog open={files} onOpenChange={setFiles}><DialogContent className="bank-dialog sm:max-w-3xl"><DialogHeader><DialogTitle>Imported sources</DialogTitle><DialogDescription>11 bank exports, the Money Manager backup, and the original app ZIP.</DialogDescription></DialogHeader><div className="source-files">{report.files.map(f=><a key={f.id} href={'/api/files?id='+f.id}><Files size={17}/><span>{f.name}<small>{(f.bytes/1024).toFixed(1)} KB · original file</small></span><Download size={17}/></a>)}</div><div className="import-notes"><h3>How matching works</h3>{report.notes.map(n=><p key={n}>{n}</p>)}</div></DialogContent></Dialog>
 <Dialog open={mmOpen} onOpenChange={setMmOpen}><DialogContent className="bank-dialog sm:max-w-4xl"><DialogHeader><DialogTitle>Money Manager without candidates</DialogTitle><DialogDescription>{monthLabel(month)} · No matching amount/date candidate in these exports. This does not prove a bank transaction is missing.</DialogDescription></DialogHeader><div className="queue-list">{mmMonth.slice(mmPage*50,(mmPage+1)*50).map(t=><div className="mm-row" key={t.id}><span><strong>{t.description||'Unlabelled'}</strong><small>{t.date} · {t.account}</small></span><strong>{money(t)}</strong></div>)}</div><div className="pagination"><button disabled={!mmPage} onClick={()=>setMmPage(p=>p-1)}>Previous</button><span>Page {mmPage+1} / {Math.max(1,Math.ceil(mmMonth.length/50))}</span><button disabled={(mmPage+1)*50>=mmMonth.length} onClick={()=>setMmPage(p=>p+1)}>Next</button></div></DialogContent></Dialog>
 </main>;
}
